language: go
go:
- 1.5
- 1.6
- 1.7
- 1.8
- 1.9
- "1.10"
- 1.11
- 1.12
sudo: required
addons:
  apt:
    packages:
      - docker-ce
cache:
  apt: true
  directories:
  - $HOME/.gimme
  - "$HOME/google-cloud-sdk/"
env:
  global:
  - GO15VENDOREXPERIMENT=1
install:
- true
script:
- ./.scripts/test_all.sh
before_deploy:
- if [[ "$TRAVIS_TAG" != "" ]]; then ./.scripts/build_all.sh; fi
deploy:
- provider: releases
  api_key:
    secure: dV3wr9ebEps3YrzIoqmkYc7fw0IECz7QLPRENPSxTJyd5TTYXGsnTS26cMe2LdGwYrXw0njt2GGovMyBZFTtxyYI3mMO4AZRwvZfx/yGzPWJBbVi6NjZVRg/bpyK+mQJ5BUlkPAYJmRpdc6qD+nvCGakBOxoByC5XDK+yM+bKFs=
  file_glob: true
  file: tusd_*.*
  skip_cleanup: true
  on:
    tags: true
    go: 1.12
    repo: tus/tusd
- provider: script
  script: .scripts/deploy_kube.sh
  on:
    branch: change-cloud
    go: 1.12
    repo: tus/tusd
