apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tusd
  namespace: tus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tusd
    spec:
      containers:
      - image: docker.io/tusproject/tusd:latest
        imagePullPolicy: Always
        args: ["-port=8080","-behind-proxy","-max-size=1000000000"]
        name: tusd
        resources:
          limits:
            cpu: 0.7
            memory: "2Gi"
          requests:
            cpu: 0.5
            memory: "1Gi"
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 1000
        volumeMounts:
        - name: tusd-disk
          mountPath: /srv/tusd-data
      volumes:
      - name: tusd-disk
        persistentVolumeClaim:
          claimName: tusd
