apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tusd
  namespace: tus
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  tls:
  - hosts:
    - thesocialcactus.com
    secretName: tusd-tls
  rules:
  - host: thesocialcactus.com
    http:
      paths:
      - path: /
        backend:
          serviceName: tusd
          servicePort: 80

